name: Build

on:
  push:
    branches:
      - env/dev
      - env/prod

jobs:
  nextjs:
    name: NextJS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build NextJS
        run: npm run build